### ISSUE TITLE
support version 3.17

### ISSUE THREAD

**Issue by Extrawurst** [DerelictOrg/DerelictFI#4]
just recently a new version came out: http://freeimage.sourceforge.net/changeslog.html
no idea what has changed but maybe good to have it on the radar

**Comment by aldacron** [comment]
Thanks for the heads up. I'll look into it as soon as I can make the time.

**Comment by marcioapm** [comment]
:+1:

Particularly interested in binding for FreeImage_RescaleRect
Currently having to fallback to copy + rescale, which sucks

**Comment by aldacron** [comment]
OK guys, sorry for taking so long to get to this. I've gone through and updated everything first to 3.16.0 and then to 3.17.0. I've also added support for DerelictUtil 2.0.0 to master and created a new 2.0 branch. For 3.17.0 features, use 2.0.0 as your derelict-fi dependency in DUB.
