### ISSUE TITLE
Program crashing on DerelictFI.load()

### ISSUE THREAD

**Issue by MoodleLadyCow** [DerelictOrg/DerelictFI#7]
I'm working on a 64x Linux Mint 17 computer and I've been having trouble getting any branch of DerelictFI to work, it'd just crash whenever I tried to run a program that loaded it.

I got it working after commenting out the following in freeimage.d:
```
myBindFunc( FreeImage_GetMemorySize, "FreeImage_GetMemorySize");
myBindFunc( FreeImage_ConvertFromRawBitsEx, "FreeImage_ConvertFromRawBitsEx" );
myBindFunc( FreeImage_ConvertToRGBAF, "FreeImage_ConvertToRGBAF" );
myBindFunc( FreeImage_ConvertToRGBAF, "FreeImage_ConvertToRGBAF" );
myBindFunc( FreeImage_SetMetadataKeyValue, "FreeImage_SetMetadataKeyValue" );
myBindFunc( FreeImage_JPEGTransformFromHandle, "FreeImage_JPEGTransformFromHandle" );
myBindFunc( FreeImage_JPEGTransformCombined, "FreeImage_JPEGTransformCombined" );
myBindFunc( FreeImage_JPEGTransformCombinedU, "FreeImage_JPEGTransformCombinedU" );
myBindFunc( FreeImage_JPEGTransformCombinedFromMemory, "FreeImage_JPEGTransformCombinedFromMemory" );
myBindFunc( FreeImage_RescaleRect, "FreeImage_RescaleRect" );
myBindFunc( FreeImage_CreateView, "FreeImage_CreateView" );
```
All of the above were throwing exceptions like: No symbol "FreeImage_RescaleRect" in current context.

**Comment by aldacron** [comment]
There's a big difference between a crash and an exception being thrown, so this isn't a crash :)

DerelictFI is implemented against FreeImage 3.17.0. All of the functions you listed here were added in either 3.16.0 or 3.17.0. That means you have an older version of FreeImage installed. There are two things you can do to resolve this. One is to upgrade to the latest version of FreeImage. While I do recommend that to take advantage of any bug fixes, it's not really good enough by itself. If you release your app, your users will face the same issue.

The other, recommended solution, is to take advantage of the SharedLibraryVersion feature in DerelictFI (and a few other Derelict packages). I haven't written the documentation for it yet here, but I wrote a couple of blog posts about it at http://dblog.aldacron.net/2015/05/derelictfi-2-0-0-supports-freeimage-3-17-0/ and http://dblog.aldacron.net/2015/05/derelictfi-2-0-1/.

Essentially, if you don't need to use any of the newer functions, then you should only try to load the lowest version possible. Apparently, you have 3.15.4 or lower on your system.3.15.4 added the function FreeImage_ConvertToRGB16. If you don't need that or any of the functions you've listed here, then call the load method like so:

```
import derelict.util.loader;
DerelictFI.load(SharedLibVersion(3, 15, 0));
```
That's the lowest version DerelictFI supports and is fairly well supported through the various Linux distro package managers. If you do need FreeImage_ConvertToRGB16, then you should load as:

```
DerelictFI.load(SharedLibVersion(3, 15, 4));
```
And so on.

**Comment by MoodleLadyCow** [comment]
Thanks! This helped a lot.

Turns out I'm a total meat-head. I thought I'd installed the latest version of FreeImage (3.17.0) using the packages listed on launchpad (https://launchpad.net/ubuntu/+source/freeimage) and if I'd scrolled down just a little I'd have read the actual version (3.15.4-4.1).

Thanks so much for explaining this to me, I've got it loading properly now with the lowest supported version :)

**Comment by aldacron** [comment]
Good news. FWIW, this thread motivated me to take some time to add a section about SharedLibVersion to the Derelict docs. Did some refactoring and editing, too. I'll be happy when I have time to finish it all.

http://derelictorg.github.io/
