### ISSUE TITLE
FreeImage 3.17 in some popular distros does not include the JPEGTransform family of function

### ISSUE THREAD

**Issue by marcioapm** [DerelictOrg/DerelictFI#9]
It seems like the 3.17 in Ubuntu and ArchLinux at least do not include these functions, due to security reasons. I think these functions require a patch to libjpeg.

Perhaps a D version to include or disable these functions would be sufficient?

**Comment by mdparker** [comment]
You can already handle this by using Derelict's selective loading mechanism. See the section titled **Selective Symbol Loading** at http://derelictorg.github.io/loading/failure/.

**Comment by Ondra09** [comment]
Linka above is broken.

**Comment by mdparker** [comment]
Fixed.

**Comment by mdparker** [comment]
BTW, if you're writing new programs with DerelictFI, I suggest using [bindbc-freeimage](https://github.com/BindBC/bindbc-freeimage) instead. The Derelict packages are in maintenance mode and I'm no longer updating them. Once I've finished porting them to BindBC, they'll be considered deprecated.

**Comment by Ondra09** [comment]
wow, that was quick. I am trying to fix my very-old project. Thank you a lot for suggestion, I will switch to bindbc-freeimage
.
